### PR TITLE
DP-3225 Wait time aria role

### PR DESCRIPTION
**Pull request by mrossi113**
To update the "Wait Time" with the aria role role="status" aria-live=“polite” to let the screen reader know when a change to the wait time has occurred.

JIRA ticket https://jira.state.ma.us/browse/DP-3225

Testing:
@jesconstantine next steps in testing this with Drupal before merging it. Tried to test in the local instance did not work.

**Note**
Added the line into the Readme file within the local working section. 
Need to discuss some items from running the `npm installed`

screen shot 2017-07-14 at 3 59 07 pm
Just to note the dist/jus/bundle.js got updated for when running npm installed.

screen shot 2017-07-14 at 3 59 23 pm

### CODE REVIEW

**Comment by mrossi113** [comment]
The `dist/js/bundle.js` needed to be updated per screenshots above this commit will update those settings. This needs to be reviewed before merging.

**Comment by mrossi113** [comment]
@jesconstantine this is ready to be reviewed I added the aria labels to each of the titles and the refresh time. Moved the role="status" aria-live=“polite” to the updated time so each time it updates it will only say the time not the whole iFrame. The reason being this would update every minute. If you think of anything else or any changes are needed let me know.

I tested this by using the following URL `http://localhost:3000/?town=Natick` in the Drupal `mass.local` within the `http://mass.local/locations/natick-rmv-service-center` page itself.

**Comment by jesconstantine** [comment]
@mrossi113 See how this works for you.  I ended up rendering any time changes in a new aria live div so that we could announce only what we want to announce, when it's changed.  (Rather than announcing new updates every minute just because the timestamp updates. )

I also rolled back the change to moment.js which likely happened when you ran npm install.

**Comment by mrossi113** [comment]
@jesconstantine that worked much better than what I had. I used both the Boston and Natick to see if this worked correctly which it did. 

The `npm install` did update the moment.js which anytime a developer runs will get modified `dist/js/bundle.js` so if the 2.17.1 is need maybe added to the readme to discard before committing to a PR. Also the CircleCI has failed with the rollback from 2.18.1 -> 2.17.1 during the `npm run test`.

**Comment by mrossi113** [comment]
@jesconstantine just updated the `Implementing the widget` section. Do you want to merge this or should I?

**Pull request merged**
